---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-db-creds-secret 
spec:
  provider: vault
  secretObjects:
    - secretName: vault-db-creds-secret
      type: Opaque
      data:
        - objectName: dbUsername # References dbUsername below
          key: username # Key within k8s secret for this value
        - objectName: dbPassword
          key: password
  parameters:
    roleName: 'example'
    vaultAddress: 'http://192.168.79.1:8200'
    vaultKubernetesMountPath: 'k8s/vaultCSI'
    objects: |
      - objectName: "dbUsername"
        secretPath: "secret/data/database/mysql/dev"
        secretKey: "username"
      - objectName: "dbPassword"
        secretPath: "secret/data/database/mysql/dev"
        secretKey: "password"
---        
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-example2
  namespace: default 
  labels:
    app: demo-app2
spec:
  selector:
    matchLabels:
      app: demo-app2
  replicas: 1
  template:
    metadata:
      annotations: {}
      labels:
        app: demo-app2
    spec:
      serviceAccountName: myapp-csi-sa
      containers:
        - name: app
          image: busybox:latest
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vault-db-creds-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vault-db-creds-secret
                  key: password
          resources:
            requests:
              memory: "32Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"
          volumeMounts:
            - name: 'vault-db-creds-vol'
              mountPath: '/mnt/secrets-store'
              readOnly: true
      volumes:
        - name: vault-db-creds-vol
          csi:
            driver: 'secrets-store.csi.k8s.io'
            readOnly: true
            volumeAttributes:
              secretProviderClass: 'vault-db-creds-secret'              